### ISSUE TITLE
Unable to install python `termcolor` package (installed with `tensorflow`) in `rocker/ml`

### ISSUE THREAD

**Issue by cryanking** [rocker-org/rocker-versioned2#484]
### Container image name

rocker/ml:latest

### Container image digest

rocker/ml@sha256:88d2d7ea949303cf5dffeab229160706e05b4d78c0fe47e4b1670d80ee8b0cb8

### What operating system are you seeing the problem on?

Linux

### System information

Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:03:45 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:02:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

CentOS 7 (but reproduces on other linux)

### Bug description

Installing tensorflow fails due to failure to install termcolor dependency. Slightly older builds (like digest sha256:f1dd01a7a75a0298d1f12f5c3c465c6633b1eb3c9f1dbaa851b6376e87a6c286) don't have this problem. 

[bug.txt](https://github.com/rocker-org/rocker-versioned2/files/8883891/bug.txt)

### How to reproduce this bug?

```sh
docker run --rm rocker/ml@sha256:88d2d7ea949303cf5dffeab229160706e05b4d78c0fe47e4b1670d80ee8b0cb8 R -e 'install.packages("tensorflow") ; library(tensorflow) ; tensorflow::install_tensorflow()'

docker run --rm rocker/ml@sha256:88d2d7ea949303cf5dffeab229160706e05b4d78c0fe47e4b1670d80ee8b0cb8 pip install tensorflow
```

Installing in pip has the same problem, this isn't an R or reticulate problem

**Comment by eitsupi** [comment]
Hi, I tried to install tensorflow on `rocker/ml@sha256:f1dd01a7a75a0298d1f12f5c3c465c6633b1eb3c9f1dbaa851b6376e87a6c286` as follows but it failed.

```sh
$ docker run --rm -it rocker/ml@sha256:f1dd01a7a75a0298d1f12f5c3c465c6633b1eb3c9f1dbaa851b6376e87a6c286 pip install tensorflow
Collecting tensorflow
  Downloading tensorflow-2.9.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (511.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.7/511.7 MB 3.3 MB/s eta 0:00:00
Collecting astunparse>=1.6.0
  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting h5py>=2.9.0
  Downloading h5py-3.7.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 10.0 MB/s eta 0:00:00
Collecting termcolor>=1.1.0
  Downloading termcolor-1.1.0.tar.gz (3.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8ubu28tb/termcolor_946cb8a21bb242f5806b906a83e33977/setup.py", line 37, in <module>
          setup(name='termcolor',
        File "/opt/venv/reticulate/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/opt/venv/reticulate/lib/python3.8/site-packages/setuptools/dist.py", line 472, in __init__
          _Distribution.__init__(
        File "/opt/venv/reticulate/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 293, in __init__
          self.finalize_options()
        File "/opt/venv/reticulate/lib/python3.8/site-packages/setuptools/dist.py", line 895, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/opt/venv/reticulate/lib/python3.8/site-packages/setuptools/dist.py", line 894, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/opt/venv/reticulate/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 196, in load
          return functools.reduce(getattr, attrs, module)
      AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

The error occurs during `termcolor` installation, but it seems that this package has not been updated for 10 years.
And, this problem is not reproduced in python:3.8.

```sh
$ docker run --rm -it python:3.8 pip install termcolor
Collecting termcolor
  Downloading termcolor-1.1.0.tar.gz (3.9 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: termcolor
  Building wheel for termcolor (setup.py) ... done
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4848 sha256=d07390450673a6058693f2f49c4211c33c02b79f0333e7b54ef831a76d8e331d
  Stored in directory: /root/.cache/pip/wheels/a0/16/9c/5473df82468f958445479c59e784896fa24f4a5fc024b0f501
Successfully built termcolor
Installing collected packages: termcolor
Successfully installed termcolor-1.1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
```

**Comment by cryanking** [comment]
In the older build, reticulate uses setup.py instead of pip / wheel to install termcolor. I don't know enough about the configurations to say how that was triggered. The older build was on python 3.8.10
```
docker run --rm -it rocker/ml@sha256:f1dd01a7a75a0298d1f12f5c3c465c6633b1eb3c9f1dbaa851b6376e87a6c286 python --version
Python 3.8.10

docker run --rm rocker/ml@sha256:f1dd01a7a75a0298d1f12f5c3c465c6633b1eb3c9f1dbaa851b6376e87a6c286 R -e 'install.packages("tensorflow") ; library(tensorflow) ; tensorflow::install_tensorflow()'

R version 4.2.0 (2022-04-22) -- "Vigorous Calisthenics"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages("tensorflow") ; library(tensorflow) ; tensorflow::install_tensorflow()
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
also installing the dependencies ‘config’, ‘tfruns’, ‘tfautograph’

trying URL 'https://packagemanager.rstudio.com/cran/__linux__/focal/latest/src/contrib/config_0.3.1.tar.gz'
Content type 'binary/octet-stream' length 79926 bytes (78 KB)
==================================================
downloaded 78 KB

trying URL 'https://packagemanager.rstudio.com/cran/__linux__/focal/latest/src/contrib/tfruns_1.5.0.tar.gz'
Content type 'binary/octet-stream' length 1485361 bytes (1.4 MB)
==================================================
downloaded 1.4 MB

trying URL 'https://packagemanager.rstudio.com/cran/__linux__/focal/latest/src/contrib/tfautograph_0.3.2.tar.gz'
Content type 'binary/octet-stream' length 161177 bytes (157 KB)
==================================================
downloaded 157 KB

trying URL 'https://packagemanager.rstudio.com/cran/__linux__/focal/latest/src/contrib/tensorflow_2.9.0.tar.gz'
Content type 'binary/octet-stream' length 200377 bytes (195 KB)
==================================================
downloaded 195 KB

* installing *binary* package ‘config’ ...
* DONE (config)
* installing *binary* package ‘tfautograph’ ...
* DONE (tfautograph)
* installing *binary* package ‘tfruns’ ...
* DONE (tfruns)
* installing *binary* package ‘tensorflow’ ...
* DONE (tensorflow)

The downloaded source packages are in
	‘/tmp/RtmpNYgW7f/downloaded_packages’
Using virtual environment '/opt/venv/reticulate' ...
+ '/opt/venv/reticulate/bin/python' -m pip install --upgrade --ignore-installed 'tensorflow==2.9.*'
Collecting tensorflow==2.9.*
  Downloading tensorflow-2.9.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (511.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.7/511.7 MB 4.3 MB/s eta 0:00:00
Collecting typing-extensions>=3.6.6
  Downloading typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Collecting wrapt>=1.11.0
  Downloading wrapt-1.14.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.0/81.0 kB 17.5 MB/s eta 0:00:00
Collecting six>=1.12.0
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting packaging
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 kB 7.5 MB/s eta 0:00:00
Collecting keras<2.10.0,>=2.9.0rc0
  Downloading keras-2.9.0-py2.py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 42.6 MB/s eta 0:00:00
Collecting flatbuffers<2,>=1.12
  Downloading flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Collecting libclang>=13.0.0
  Downloading libclang-14.0.1-py2.py3-none-manylinux1_x86_64.whl (14.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.5/14.5 MB 40.2 MB/s eta 0:00:00
Collecting protobuf<3.20,>=3.9.2
  Downloading protobuf-3.19.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 52.5 MB/s eta 0:00:00
Collecting astunparse>=1.6.0
  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting opt-einsum>=2.3.2
  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 15.3 MB/s eta 0:00:00
Collecting keras-preprocessing>=1.1.1
  Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 8.0 MB/s eta 0:00:00
Collecting numpy>=1.20
  Downloading numpy-1.22.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.9/16.9 MB 38.8 MB/s eta 0:00:00
Collecting tensorboard<2.10,>=2.9
  Downloading tensorboard-2.9.1-py3-none-any.whl (5.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 43.9 MB/s eta 0:00:00
Collecting h5py>=2.9.0
  Downloading h5py-3.7.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 47.3 MB/s eta 0:00:00
Collecting gast<=0.4.0,>=0.2.1
  Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting grpcio<2.0,>=1.24.3
  Downloading grpcio-1.46.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 48.2 MB/s eta 0:00:00
Collecting google-pasta>=0.1.1
  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 15.8 MB/s eta 0:00:00
Collecting setuptools
  Downloading setuptools-62.3.4-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 44.4 MB/s eta 0:00:00
Collecting tensorflow-io-gcs-filesystem>=0.23.1
  Downloading tensorflow_io_gcs_filesystem-0.26.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 13.7 MB/s eta 0:00:00
Collecting termcolor>=1.1.0
  Downloading termcolor-1.1.0.tar.gz (3.9 kB)
  Preparing metadata (setup.py) ... done
Collecting tensorflow-estimator<2.10.0,>=2.9.0rc0
  Downloading tensorflow_estimator-2.9.0-py2.py3-none-any.whl (438 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 438.7/438.7 kB 45.4 MB/s eta 0:00:00
Collecting absl-py>=1.0.0
  Downloading absl_py-1.1.0-py3-none-any.whl (123 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.7/123.7 kB 29.0 MB/s eta 0:00:00
Collecting wheel<1.0,>=0.23.0
  Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Collecting markdown>=2.6.8
  Downloading Markdown-3.3.7-py3-none-any.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.8/97.8 kB 14.7 MB/s eta 0:00:00
Collecting requests<3,>=2.21.0
  Downloading requests-2.28.0-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 14.6 MB/s eta 0:00:00
Collecting tensorboard-plugin-wit>=1.6.0
  Downloading tensorboard_plugin_wit-1.8.1-py3-none-any.whl (781 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.3/781.3 kB 50.3 MB/s eta 0:00:00
Collecting google-auth<3,>=1.6.3
  Downloading google_auth-2.7.0-py2.py3-none-any.whl (160 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.7/160.7 kB 37.1 MB/s eta 0:00:00
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Downloading google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Collecting werkzeug>=1.0.1
  Downloading Werkzeug-2.1.2-py3-none-any.whl (224 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.9/224.9 kB 30.7 MB/s eta 0:00:00
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Downloading tensorboard_data_server-0.6.1-py3-none-manylinux2010_x86_64.whl (4.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 47.1 MB/s eta 0:00:00
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 18.0 MB/s eta 0:00:00
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.8-py3-none-any.whl (39 kB)
Collecting cachetools<6.0,>=2.0.0
  Downloading cachetools-5.2.0-py3-none-any.whl (9.3 kB)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 37.0 MB/s eta 0:00:00
Collecting requests-oauthlib>=0.7.0
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Collecting importlib-metadata>=4.4
  Downloading importlib_metadata-4.11.4-py3-none-any.whl (18 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.0/139.0 kB 25.5 MB/s eta 0:00:00
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2022.5.18.1-py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.2/155.2 kB 24.3 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 16.2 MB/s eta 0:00:00
Collecting zipp>=0.5
  Downloading zipp-3.8.0-py3-none-any.whl (5.4 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 16.0 MB/s eta 0:00:00
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.2.0-py3-none-any.whl (151 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.5/151.5 kB 28.2 MB/s eta 0:00:00
Using legacy 'setup.py install' for termcolor, since package 'wheel' is not installed.
Installing collected packages: termcolor, tensorboard-plugin-wit, pyasn1, libclang, keras, flatbuffers, zipp, wrapt, wheel, werkzeug, urllib3, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, six, setuptools, rsa, pyparsing, pyasn1-modules, protobuf, oauthlib, numpy, idna, gast, charset-normalizer, certifi, cachetools, absl-py, requests, packaging, opt-einsum, keras-preprocessing, importlib-metadata, h5py, grpcio, google-pasta, google-auth, astunparse, requests-oauthlib, markdown, google-auth-oauthlib, tensorboard, tensorflow
  Running setup.py install for termcolor ... done
Successfully installed absl-py-1.1.0 astunparse-1.6.3 cachetools-5.2.0 certifi-2022.5.18.1 charset-normalizer-2.0.12 flatbuffers-1.12 gast-0.4.0 google-auth-2.7.0 google-auth-oauthlib-0.4.6 google-pasta-0.2.0 grpcio-1.46.3 h5py-3.7.0 idna-3.3 importlib-metadata-4.11.4 keras-2.9.0 keras-preprocessing-1.1.2 libclang-14.0.1 markdown-3.3.7 numpy-1.22.4 oauthlib-3.2.0 opt-einsum-3.3.0 packaging-21.3 protobuf-3.19.4 pyasn1-0.4.8 pyasn1-modules-0.2.8 pyparsing-3.0.9 requests-2.28.0 requests-oauthlib-1.3.1 rsa-4.8 setuptools-62.3.4 six-1.16.0 tensorboard-2.9.1 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.1 tensorflow-2.9.1 tensorflow-estimator-2.9.0 tensorflow-io-gcs-filesystem-0.26.0 termcolor-1.1.0 typing-extensions-4.2.0 urllib3-1.26.9 werkzeug-2.1.2 wheel-0.37.1 wrapt-1.14.1 zipp-3.8.0
WARNING: There was an error checking the latest version of pip.

Installation complete.
```

**Comment by eitsupi** [comment]
We can compare the two images here, and there does not appear to be a significant difference...
The version of reticulate seems to be exactly the same.

https://github.com/rocker-org/rocker-versioned2/wiki/ml_81602e74cea7
https://github.com/rocker-org/rocker-versioned2/wiki/ml_e78d539e1566
https://github.com/rocker-org/rocker-versioned2/compare/ba73e4ab96225c466f5fc1d7b9831da591c54c32...a6c18b3663f058b2fe037546cdf89a347651363e

**Comment by eitsupi** [comment]
@cryanking I can't repro this.

```sh
$ docker run --rm rocker/ml@sha256:f1dd01a7a75a0298d1f12f5c3c465c6633b1eb3c9f1dbaa851b6376e87a6c286 R -e 'install.packag
es("tensorflow") ; library(tensorflow) ; tensorflow::install_tensorflow()'

R version 4.2.0 (2022-04-22) -- "Vigorous Calisthenics"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages("tensorflow") ; library(tensorflow) ; tensorflow::install_tensorflow()
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
also installing the dependencies ‘config’, ‘tfruns’, ‘tfautograph’

trying URL 'https://packagemanager.rstudio.com/cran/__linux__/focal/latest/src/contrib/config_0.3.1.tar.gz'
Content type 'binary/octet-stream' length 79926 bytes (78 KB)
==================================================
downloaded 78 KB

trying URL 'https://packagemanager.rstudio.com/cran/__linux__/focal/latest/src/contrib/tfruns_1.5.0.tar.gz'
Content type 'binary/octet-stream' length 1485361 bytes (1.4 MB)
==================================================
downloaded 1.4 MB

trying URL 'https://packagemanager.rstudio.com/cran/__linux__/focal/latest/src/contrib/tfautograph_0.3.2.tar.gz'
Content type 'binary/octet-stream' length 161177 bytes (157 KB)
==================================================
downloaded 157 KB

trying URL 'https://packagemanager.rstudio.com/cran/__linux__/focal/latest/src/contrib/tensorflow_2.9.0.tar.gz'
Content type 'binary/octet-stream' length 200377 bytes (195 KB)
==================================================
downloaded 195 KB

* installing *binary* package ‘config’ ...
* DONE (config)
* installing *binary* package ‘tfautograph’ ...
* DONE (tfautograph)
* installing *binary* package ‘tfruns’ ...
* DONE (tfruns)
* installing *binary* package ‘tensorflow’ ...
* DONE (tensorflow)

The downloaded source packages are in
        ‘/tmp/Rtmptop83i/downloaded_packages’
Using virtual environment '/opt/venv/reticulate' ...
+ '/opt/venv/reticulate/bin/python' -m pip install --upgrade --ignore-installed 'tensorflow==2.9.*'
Collecting tensorflow==2.9.*
  Downloading tensorflow-2.9.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (511.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.7/511.7 MB 4.1 MB/s eta 0:00:00
Collecting gast<=0.4.0,>=0.2.1
  Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting h5py>=2.9.0
  Downloading h5py-3.7.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 14.4 MB/s eta 0:00:00
Collecting keras-preprocessing>=1.1.1
  Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 4.2 MB/s eta 0:00:00
Collecting google-pasta>=0.1.1
  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 6.7 MB/s eta 0:00:00
Collecting keras<2.10.0,>=2.9.0rc0
  Downloading keras-2.9.0-py2.py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 14.5 MB/s eta 0:00:00
Collecting tensorflow-io-gcs-filesystem>=0.23.1
  Downloading tensorflow_io_gcs_filesystem-0.26.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 15.2 MB/s eta 0:00:00
Collecting termcolor>=1.1.0
  Downloading termcolor-1.1.0.tar.gz (3.9 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-vq5g8jlj/termcolor_4a0394fde8bd4a50987e5a1cf067d793/setup.py", line 37, in <module>
          setup(name='termcolor',
        File "/opt/venv/reticulate/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/opt/venv/reticulate/lib/python3.8/site-packages/setuptools/dist.py", line 472, in __init__
          _Distribution.__init__(
        File "/opt/venv/reticulate/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 293, in __init__
          self.finalize_options()
        File "/opt/venv/reticulate/lib/python3.8/site-packages/setuptools/dist.py", line 895, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/opt/venv/reticulate/lib/python3.8/site-packages/setuptools/dist.py", line 894, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/opt/venv/reticulate/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 196, in load
          return functools.reduce(getattr, attrs, module)
      AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: There was an error checking the latest version of pip.
Error: Error installing package(s): "'tensorflow==2.9.*'"
Execution halted
```

**Comment by cryanking** [comment]
I get the same thing (able to install using f1dd01a7a75a0298d1f12f5c3c465c6633b1eb3c9f1dbaa851b6376e87a6c286, I copy and pasted the command from your post) on 3 machines running different linux variants. I don't know why, but maybe geography affects the repo being hit?

**Comment by eitsupi** [comment]
I don't know why (I know very little about pip), but it seems that pip installs packages in a different order in your case than in mine?
I can't say that this is not due to geographical conditions (i.e. communication conditions with the server)...
It is really odd.

**Comment by cryanking** [comment]
This bug is discussed in a few places:
https://github.com/pypa/setuptools/issues/3118
https://github.com/pypa/setuptools/issues/2765
https://github.com/pypa/pip/issues/7616

It seems to be caused by setuptools allowing configs from old versions to inherit on top of new ones, and be limited to python 3.8 and setuptools > 60.8.2 . It's a pretty difficult to isolate issue. Anyway, the following works:
```
docker run --rm rocker/ml:latest R -e 'library(reticulate); py_install("setuptools==60.8.2"); install.packages("tensorflow") ; library(tensorflow) ; tensorflow::install_tensorflow()'
```
Of course you can do the same directly with pip (but it does need to be 2 commands to allow setuptools to finish downgrading). Unless there is something that requires it, maybe the installed setuptools should be pinned at 60.8.2 until python 3.9 is in the base image?

**Comment by cryanking** [comment]
Well, if you downgrade setuptools in the docker build, then unless users update it they will avoid the bug. It's also possible that the bad setuptools config is somehow leaking in, but the above are all with no volumes passed from the OS and no additional build context. Actually finding the old setuptools config is probably hard

**Comment by eitsupi** [comment]
There seems to be no need to upgrade setuptools here.

https://github.com/rocker-org/rocker-versioned2/blob/29e6572ae189085e22b24e821a65ce6e2b1aa72b/scripts/install_python.sh#L31-L34
