### ISSUE TITLE
rocker/shiny: running Shiny _app_ as root?

### ISSUE THREAD

**Issue by mmuurr** [rocker-org/rocker-versioned2#519]
### Container image name

rocker/shiny:4.2.1

### Container image digest

rocker/shiny@sha256:b69d633a33c2a6afc49b24468bf2bc9449358e581331b05672652c31b6af688e

### What operating system related to this question?

macOS

### Question

Hi, I'm using rocker/shiny and am stumbling in one scenario -- but only with the Docker images.
Here's an example `Dockerfile`:

```dockerfile
# syntax=docker/dockerfile:1.4
FROM rocker/shiny:4.2.1
COPY shiny-server.conf /etc/shiny-server/shiny-server.conf
```

... and here's the `shiny-server.conf`:

```
run_as root;
server {
  listen 3838;
  location / {
    site_dir /srv/shiny-server;
    log_dir /var/log/shiny-server;
    directory_index on;
  }
}
```

This is the out-of-the-box default `shiny-server.conf`, but with `run_as` set to `root` (instead of `shiny`). That is to say, I'd like to run the _Shiny apps_ (as well as Shiny Server) as `root`.

Most questions around this topic revolve around running Shiny Server as user `shiny` (or some other non-`root`) user, and it'd make perfect sense that `shiny` would fail to run a Shiny app as `root`.
But I'm experiencing the other problem: I've validated that Shiny Server itself is running as `root`, yet is failing to launch Shiny apps also as `root`.
When setting the Shiny Server log-level to `TRACE`, here's the log output from the standard Shiny Server demo page:

```
[2022-08-22T18:50:45.664] [INFO] shiny-server - Shiny Server v1.5.18.979 (Node.js v12.22.6)
[2022-08-22T18:50:45.666] [DEBUG] shiny-server - No pidfile requested
[2022-08-22T18:50:45.667] [INFO] shiny-server - Using config file "/etc/shiny-server/shiny-server.conf"
[2022-08-22T18:50:45.717] [WARN] shiny-server - Running as root unnecessarily is a security risk! You could be running more securely as non-root.
[2022-08-22T18:50:45.721] [INFO] shiny-server - Starting listener on http://[::]:3838
[2022-08-22T18:50:45.721] [DEBUG] shiny-server - Actual addr: ::
[2022-08-22T18:50:45.721] [DEBUG] shiny-server - Actual port: 3838
[2022-08-22T18:50:45.724] [DEBUG] shiny-server - No access log configured
[2022-08-22T18:50:45.725] [TRACE] shiny-server - Config loaded
[2022-08-22T18:50:56.187] [TRACE] shiny-server - Spawning new instance
[2022-08-22T18:50:56.189] [TRACE] shiny-server - Worker #4d5fba971919230f acquiring http port. 1 HTTP, 0 WebSocket, 0 pending.
[2022-08-22T18:50:56.190] [TRACE] shiny-server - Worker #4d5fba971919230f acquiring pending port. 1 HTTP, 0 WebSocket, 1 pending.
[2022-08-22T18:50:56.196] [TRACE] shiny-server - Launching /srv/shiny-server/sample-apps/rmd as root with on port 42163
[2022-08-22T18:50:56.197] [TRACE] shiny-server - Spawning new instance
[2022-08-22T18:50:56.198] [TRACE] shiny-server - Worker #470b606d021d8d6d acquiring http port. 1 HTTP, 0 WebSocket, 0 pending.
[2022-08-22T18:50:56.198] [TRACE] shiny-server - Worker #470b606d021d8d6d acquiring pending port. 1 HTTP, 0 WebSocket, 1 pending.
[2022-08-22T18:50:56.200] [TRACE] shiny-server - Launching /srv/shiny-server/sample-apps/hello as root with on port 36453
[2022-08-22T18:50:56.205] [TRACE] shiny-server - Starting R
[2022-08-22T18:50:56.205] [TRACE] shiny-server - Error: Aborting attempt to launch R process as root
    at new AppWorker (/opt/shiny-server/lib/worker/app-worker.js:282:13)
    at /opt/shiny-server/lib/worker/app-worker.js:155:22
    at _fulfilled (/opt/shiny-server/node_modules/q/q.js:854:54)
    at /opt/shiny-server/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/opt/shiny-server/node_modules/q/q.js:816:13)
    at /opt/shiny-server/node_modules/q/q.js:624:44
    at runSingle (/opt/shiny-server/node_modules/q/q.js:137:13)
    at flush (/opt/shiny-server/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2022-08-22T18:50:56.209] [TRACE] shiny-server - Aborting connection attempts to port 42163
[2022-08-22T18:50:56.210] [TRACE] shiny-server - Subprocess failed to start, removing worker entry
[2022-08-22T18:50:56.211] [TRACE] shiny-server - Port 42163 returned
[2022-08-22T18:50:56.211] [INFO] shiny-server - Error getting worker: Error: Connection attempt was aborted.
[2022-08-22T18:50:56.213] [TRACE] shiny-server - Starting R
[2022-08-22T18:50:56.213] [TRACE] shiny-server - Error: Aborting attempt to launch R process as root
    at new AppWorker (/opt/shiny-server/lib/worker/app-worker.js:282:13)
    at /opt/shiny-server/lib/worker/app-worker.js:155:22
    at _fulfilled (/opt/shiny-server/node_modules/q/q.js:854:54)
    at /opt/shiny-server/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/opt/shiny-server/node_modules/q/q.js:816:13)
    at /opt/shiny-server/node_modules/q/q.js:624:44
    at runSingle (/opt/shiny-server/node_modules/q/q.js:137:13)
    at flush (/opt/shiny-server/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2022-08-22T18:50:56.214] [TRACE] shiny-server - Aborting connection attempts to port 36453
[2022-08-22T18:50:56.214] [TRACE] shiny-server - Subprocess failed to start, removing worker entry
[2022-08-22T18:50:56.217] [TRACE] shiny-server - Port 36453 returned
[2022-08-22T18:50:56.217] [INFO] shiny-server - Error getting worker: Error: Connection attempt was aborted.
[2022-08-22T18:50:56.272] [TRACE] shiny-server - Worker #4d5fba971919230f releasing http port. 0 HTTP, 0 WebSocket, 1 pending.
[2022-08-22T18:50:56.272] [TRACE] shiny-server - Worker #4d5fba971919230f releasing pending port. 0 HTTP, 0 WebSocket, 0 pending.
[2022-08-22T18:50:56.272] [TRACE] shiny-server - No clients connected to worker #4d5fba971919230f. Starting timer
[2022-08-22T18:50:56.274] [TRACE] shiny-server - Worker #470b606d021d8d6d releasing http port. 0 HTTP, 0 WebSocket, 1 pending.
[2022-08-22T18:50:56.274] [TRACE] shiny-server - Worker #470b606d021d8d6d releasing pending port. 0 HTTP, 0 WebSocket, 0 pending.
[2022-08-22T18:50:56.274] [TRACE] shiny-server - No clients connected to worker #470b606d021d8d6d. Starting timer

*** '/var/log/shiny-server//hello-root-20220822-185056-36453.log' has been created ***

*** '/var/log/shiny-server//rmd-root-20220822-185056-42163.log' has been created ***

*** /var/log/shiny-server//hello-root-20220822-185056-36453.log ***

*** /var/log/shiny-server//rmd-root-20220822-185056-42163.log ***
[2022-08-22T18:51:01.274] [TRACE] shiny-server - Timeout expired. Killing process.
[2022-08-22T18:51:01.275] [TRACE] shiny-server - Interrupting process on socket port 42163
[2022-08-22T18:51:01.276] [TRACE] shiny-server - Timeout expired. Killing process.
[2022-08-22T18:51:01.277] [TRACE] shiny-server - Interrupting process on socket port 36453
```

The relevant entries are mostly the `Launching /srv/shiny-server/sample-apps/hello as root` and `Error: Aborting attempt to launch R process as root` lines.
The application logs themselves remain completely empty (since the R process was never spawned).
And in the web interface, the apps just get a standard error display:
<img width="282" alt="image" src="https://user-images.githubusercontent.com/5702538/185997816-ce5ba8bf-3aa7-4234-99bb-4ef29e244f52.png">

Is there any known reason as to why Shiny Server running as `root` cannot spawn another process owned by `root`?

I've validated in a non-Docker setup (on a Debian AWS AMI) that `run_as root` works fine from the Shiny Server perspective, and thus so far I've only encountered this error in the Rocker images :-/ 

BTW -- I'm aware of how to restructure my Docker applications to `run_as` user `shiny` already (and have migrated my apps to that model to unblock myself), but am mostly curious about this error as there are some decent reasons in my use case to run the Shiny application itself as `root` (within the container).

Thanks for any info and all your work on the Rocker Project!

**Comment by eitsupi** [comment]
Did you solve the problem?
I will close this for now, but feel free to open it again.
